-- Indices na tabela rental pra melhorar performance

CREATE INDEX IDX_RENTAL_CUSTOMER_RENTAL_DATE 
ON RENTAL (CUSTOMER_ID, RENTAL_DATE);

CREATE INDEX IDX_CUSTOMER_CUSTOMER_ADDRESS
ON CUSTOMER (CUSTOMER_ID, ADDRESS_ID);