-- Indices na tabela rental pra melhorar performance

CREATE INDEX IDX_RENTAL_DATE_INVENTORY
ON RENTAL (RENTAL_DATE, INVENTORY_ID);

CREATE INDEX IDX_RENTAL_CUSTOMER_RENTAL
ON RENTAL (CUSTOMER_ID, RENTAL_ID);