-- Quantidade e valor total de empréstimos, possibilitando uma visão hierárquica ao longo do tempo

IF EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.ROUTINES 
  WHERE SPECIFIC_NAME = N'PROC_ETL_FT_RENTAL_ANALISE2' 
)
  DROP PROCEDURE PROC_ETL_FT_RENTAL_ANALISE2;

-- PROCEDURE PARA POPULAR FT_RENTAL PARA A ANÁLISE 2
CREATE PROCEDURE DBO.PROC_ETL_FT_RENTAL_ANALISE2
AS
BEGIN
  -- DECLARAÇÃO DAS VARIÁVEIS
  DECLARE
    @TIME INT,
    @QUANTITY INT,
    @AMOUNT DECIMAL(10, 2),
    @V_DSC_DADOS_PROCESSAMENTO VARCHAR(2000);

  -- CURSOR PARA CAPTURAR OS DADOS
  DECLARE CUR_GET_RENTAL CURSOR FOR
  SELECT
      dt.DIM_TEMPO_SEQ_TEMPO AS TIME,
      COUNT(r.rental_id) AS QUANTITY,
      SUM(p.amount) AS AMOUNT
  FROM
      RENTAL r
      JOIN PAYMENT p ON r.rental_id = p.rental_id
      JOIN DIM_TEMPO dt ON YEAR(r.RENTAL_DATE) = dt.DIM_TEMPO_ANO
                        AND MONTH(r.RENTAL_DATE) = dt.DIM_TEMPO_MES
  GROUP BY
      dt.DIM_TEMPO_SEQ_TEMPO;

  -- ABRE O CURSOR
  OPEN CUR_GET_RENTAL;

  -- CAPTURA O PRIMEIRO REGISTRO
  FETCH NEXT FROM CUR_GET_RENTAL INTO @TIME, @QUANTITY, @AMOUNT;

  -- LOOP PARA PROCESSAR TODOS OS REGISTROS
  WHILE (@@FETCH_STATUS = 0)
  BEGIN
    -- INFORMAÇÕES DE PROCESSAMENTO
    SET @V_DSC_DADOS_PROCESSAMENTO = 'TIME ' + CAST(@TIME AS VARCHAR);

    BEGIN TRANSACTION;
      -- INSERE OS DADOS NA FT_RENTAL
      INSERT INTO FT_RENTAL (
          TIME, FILM_ID, CATEGORY_ID, CUSTOMER_ID, STAFF_ID, STORE_ID, INVENTORY_ID, ACTOR_ID, QUANTITY, AMOUNT, STATUS_PAGAMENTO, LUCRO_PREJUIZO
      )
      VALUES (
          @TIME, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @QUANTITY, @AMOUNT, NULL, NULL
      );

      -- TRATAMENTO DE ERRO
      IF @@ERROR <> 0
      BEGIN
        ROLLBACK;
        SELECT @V_DSC_DADOS_PROCESSAMENTO;
        CLOSE CUR_GET_RENTAL;
        DEALLOCATE CUR_GET_RENTAL;
        RETURN;
      END
    COMMIT;

    -- CAPTURA O PRÓXIMO REGISTRO
    FETCH NEXT FROM CUR_GET_RENTAL INTO @TIME, @QUANTITY, @AMOUNT;
  END

  -- FECHA O CURSOR E LIBERA RECURSOS
  CLOSE CUR_GET_RENTAL;
  DEALLOCATE CUR_GET_RENTAL;
END;

EXEC DBO.PROC_ETL_FT_RENTAL_ANALISE2;

SELECT
    dt.DIM_TEMPO_ANO AS ANO,
    dt.DIM_TEMPO_MES AS MES,
    SUM(fr.QUANTITY) AS QUANTIDADE_EMPRESTIMOS,
    SUM(fr.AMOUNT) AS VALOR_TOTAL_EMPRESTIMOS
FROM
    FT_RENTAL fr
    JOIN DIM_TEMPO dt ON fr.TIME = dt.DIM_TEMPO_SEQ_TEMPO
WHERE
    fr.FILM_ID IS NULL
    AND fr.CATEGORY_ID IS NULL
    AND fr.CUSTOMER_ID IS NULL
    AND fr.STAFF_ID IS NULL
    AND fr.STORE_ID IS NULL
    AND fr.INVENTORY_ID IS NULL
    AND fr.ACTOR_ID IS NULL
GROUP BY
    dt.DIM_TEMPO_ANO,
    dt.DIM_TEMPO_MES
ORDER BY
    dt.DIM_TEMPO_ANO,
    dt.DIM_TEMPO_MES;

-- PROVA REAL

SELECT
    dt.DIM_TEMPO_SEQ_TEMPO AS TIME,
    COUNT(r.rental_id) AS QUANTIDADE_EMPRESTIMOS_ORIGINAL,
    SUM(p.amount) AS VALOR_TOTAL_ORIGINAL
FROM
    RENTAL r
    JOIN PAYMENT p ON r.rental_id = p.rental_id
    JOIN DIM_TEMPO dt ON YEAR(r.RENTAL_DATE) = dt.DIM_TEMPO_ANO
                      AND MONTH(r.RENTAL_DATE) = dt.DIM_TEMPO_MES
GROUP BY
    dt.DIM_TEMPO_SEQ_TEMPO
ORDER BY
    dt.DIM_TEMPO_SEQ_TEMPO;