-- Análise de filmes e suas quantidades por filme e categoria em cada local de armazenamento

IF EXISTS (
  SELECT * 
  FROM INFORMATION_SCHEMA.ROUTINES 
  WHERE SPECIFIC_NAME = N'PROC_ETL_FT_RENTAL_ANALISE5' 
)
  DROP PROCEDURE PROC_ETL_FT_RENTAL_ANALISE5;

-- PROCEDURE PARA POPULAR FT_RENTAL PARA A ANÁLISE 5
CREATE PROCEDURE DBO.PROC_ETL_FT_RENTAL_ANALISE5
AS
BEGIN
  -- DECLARAÇÃO DAS VARIÁVEIS
  DECLARE
    @FILM_ID INT,
    @CATEGORY_ID INT,
    @STORE_ID INT,
    @QUANTITY INT,
    @V_DSC_DADOS_PROCESSAMENTO VARCHAR(2000);

  -- CURSOR PARA CAPTURAR OS DADOS
  DECLARE CUR_GET_RENTAL CURSOR FOR
  SELECT
      f.FILM_ID,
      cat.CATEGORY_ID,
      i.STORE_ID,
      COUNT(r.rental_id) AS QUANTITY
  FROM
      RENTAL r
      JOIN INVENTORY i ON r.INVENTORY_ID = i.INVENTORY_ID
      JOIN FILM f ON i.FILM_ID = f.FILM_ID
      JOIN FILM_CATEGORY fc ON f.FILM_ID = fc.FILM_ID
      JOIN DIM_CATEGORY cat ON fc.CATEGORY_ID = cat.CATEGORY_ID
  GROUP BY
      f.FILM_ID,
      cat.CATEGORY_ID,
      i.STORE_ID;

  -- ABRE O CURSOR
  OPEN CUR_GET_RENTAL;

  -- CAPTURA O PRIMEIRO REGISTRO
  FETCH NEXT FROM CUR_GET_RENTAL INTO @FILM_ID, @CATEGORY_ID, @STORE_ID, @QUANTITY;

  -- LOOP PARA PROCESSAR TODOS OS REGISTROS
  WHILE (@@FETCH_STATUS = 0)
  BEGIN
    -- INFORMAÇÕES DE PROCESSAMENTO
    SET @V_DSC_DADOS_PROCESSAMENTO = 'FILM ' + CAST(@FILM_ID AS VARCHAR) + ', CATEGORY ' + CAST(@CATEGORY_ID AS VARCHAR) 
                                   + ', STORE ' + CAST(@STORE_ID AS VARCHAR);

    BEGIN TRANSACTION;
      -- INSERE OS DADOS NA FT_RENTAL
      INSERT INTO FT_RENTAL (
          TIME, FILM_ID, CATEGORY_ID, CUSTOMER_ID, STAFF_ID, STORE_ID, INVENTORY_ID, ACTOR_ID, QUANTITY, AMOUNT, STATUS_PAGAMENTO, LUCRO_PREJUIZO
      )
      VALUES (
          0, @FILM_ID, @CATEGORY_ID, NULL, NULL, @STORE_ID, NULL, NULL, @QUANTITY, 0.00, NULL, NULL
      );

      -- TRATAMENTO DE ERRO
      IF @@ERROR <> 0
      BEGIN
        ROLLBACK;
        SELECT @V_DSC_DADOS_PROCESSAMENTO;
        CLOSE CUR_GET_RENTAL;
        DEALLOCATE CUR_GET_RENTAL;
        RETURN;
      END
    COMMIT;

    -- CAPTURA O PRÓXIMO REGISTRO
    FETCH NEXT FROM CUR_GET_RENTAL INTO @FILM_ID, @CATEGORY_ID, @STORE_ID, @QUANTITY;
  END

  -- FECHA O CURSOR E LIBERA RECURSOS
  CLOSE CUR_GET_RENTAL;
  DEALLOCATE CUR_GET_RENTAL;
END;

EXEC DBO.PROC_ETL_FT_RENTAL_ANALISE5;

SELECT
    f.TITLE AS FILME,
    c.NAME AS CATEGORIA,
    fr.STORE_ID AS LOJA,
    SUM(fr.QUANTITY) AS QUANTIDADE_EMPRESTIMOS
FROM
    FT_RENTAL fr
    JOIN DIM_FILM f ON fr.FILM_ID = f.FILM_ID
    JOIN DIM_CATEGORY c ON fr.CATEGORY_ID = c.CATEGORY_ID
WHERE
    fr.TIME = 0
    AND fr.CUSTOMER_ID IS NULL
    AND fr.STAFF_ID IS NULL
    AND fr.INVENTORY_ID IS NULL
    AND fr.ACTOR_ID IS NULL
GROUP BY
    f.TITLE,
    c.NAME,
    fr.STORE_ID
ORDER BY
    f.TITLE,
    c.NAME,
    fr.STORE_ID;